### ISSUE TITLE
fix pylint errors

### ISSUE THREAD

**Issue by justadreamer** [postindustria-tech/pipeline-python#2]
# Background

In the upstream repository [51degrees:pipeline-python](https://github.com/51Degrees/pipeline-python) - the most build and test runs [fail](https://github.com/51Degrees/pipeline-python/actions/runs/6387476314/job/17344831856#step:5:228) due to pylint errors reported

# Objective

Fix the errors found by pylint, so that the build passes. 

# Details

Please make a fix on a separate branch in this repo and submit a PR from it to the upstream:main branch.

**Comment by BohdanVV** [comment]
Resolved with [this PR](https://github.com/51Degrees/pipeline-python/pull/14)
